/**
 * Payroll Model
 * ============================================================
 * Stores monthly payroll records per employee.
 *
 * Formula:
 * Net Salary = (Basic Salary + Allowances) - (Deductions + Tax + Loans)
 */

const mongoose = require('mongoose');

const PayrollSchema = new mongoose.Schema(
  {
    employee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: [true, 'Employee reference is required'],
    },

    // ─── Pay Period ────────────────────────────────────────────
    month: {
      type: Number,
      required: [true, 'Month is required'],
      min: 1,
      max: 12,
    },
    year: {
      type: Number,
      required: [true, 'Year is required'],
    },
    payPeriodLabel: {
      type: String, // e.g. "June 2024"
    },

    // ─── Earnings ──────────────────────────────────────────────
    basicSalary: {
      type: Number,
      required: [true, 'Basic salary is required'],
      min: 0,
    },
    allowances: {
      houseRent: { type: Number, default: 0 },
      transport: { type: Number, default: 0 },
      medical: { type: Number, default: 0 },
      food: { type: Number, default: 0 },
      other: { type: Number, default: 0 },
    },
    totalAllowances: {
      type: Number,
      default: 0,
    },
    grossSalary: {
      type: Number,
      default: 0,
    },

    // ─── Deductions ─────────────────────────────────────────────
    deductions: {
      providentFund: { type: Number, default: 0 },
      insurance: { type: Number, default: 0 },
      absence: { type: Number, default: 0 }, // Absent day deductions
      other: { type: Number, default: 0 },
    },
    tax: {
      type: Number,
      default: 0,
    },
    loans: {
      type: Number,
      default: 0,
    },
    totalDeductions: {
      type: Number,
      default: 0,
    },

    // ─── Net Salary (auto-calculated) ─────────────────────────
    netSalary: {
      type: Number,
      default: 0,
    },

    // ─── Attendance Summary for this payroll ──────────────────
    workingDays: { type: Number, default: 0 },
    presentDays: { type: Number, default: 0 },
    absentDays: { type: Number, default: 0 },
    lateDays: { type: Number, default: 0 },
    overtimeHours: { type: Number, default: 0 },
    overtimePay: { type: Number, default: 0 },

    // ─── Status & Payment ──────────────────────────────────────
    status: {
      type: String,
      enum: ['Draft', 'Generated', 'Paid', 'Cancelled'],
      default: 'Draft',
    },
    paidAt: {
      type: Date,
      default: null,
    },
    paymentMethod: {
      type: String,
      enum: ['Bank Transfer', 'Cash', 'Cheque', null],
      default: null,
    },

    // ─── Generated By ──────────────────────────────────────────
    generatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
    },

    // ─── PDF Payslip Path ──────────────────────────────────────
    payslipUrl: {
      type: String,
      default: null,
    },

    notes: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// ─── Compound Index: One payroll per employee per month/year ──────────────────
PayrollSchema.index({ employee: 1, month: 1, year: 1 }, { unique: true });

// ─── Pre-Save: Calculate totals automatically ─────────────────────────────────
PayrollSchema.pre('save', function (next) {
  // Total Allowances
  const a = this.allowances;
  this.totalAllowances = (a.houseRent || 0) + (a.transport || 0) + (a.medical || 0) + (a.food || 0) + (a.other || 0);

  // Gross Salary
  this.grossSalary = this.basicSalary + this.totalAllowances + (this.overtimePay || 0);

  // Total Deductions
  const d = this.deductions;
  this.totalDeductions =
    (d.providentFund || 0) + (d.insurance || 0) + (d.absence || 0) + (d.other || 0) + (this.tax || 0) + (this.loans || 0);

  // Net Salary
  this.netSalary = Math.max(0, this.grossSalary - this.totalDeductions);

  // Pay Period Label
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  this.payPeriodLabel = `${monthNames[this.month - 1]} ${this.year}`;

  next();
});

module.exports = mongoose.model('Payroll', PayrollSchema);
